services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # API端口
      - "9001:9001"  # 控制台端口
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./db/minio_data:/data
    command: server /data --console-address ":9001"

  mongodb:
    image: mongo:latest
    container_name: mongodb-local
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: rag
    volumes:
      - ./db/mongodb_data/db:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"     # REST API port
      - "6334:6334"     # gRPC port
    volumes:
      - ./db/qdrant_data:/qdrant/storage
    